services:
  claude-code:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: claude-code-CONTAINER_ORIGIN_NAME
    volumes:
      - ~/.claude:/home/developer/.claude/
      - .:/workspace/.ccc
      - ..:/workspace:rw
    working_dir: /workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    init: true
