services:
  claude-code-container_origin_name:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAIL_DOMAIN: ${MAIL_DOMAIN}
    env_file:
      - .env
    container_name: claude-code-container_origin_name
    volumes:
      - ~/.config/gh:/root/.config/gh:ro  # gh-cliの設定を読み取り専用で共有
      - ~/.claude:/home/ubuntu/.config/claude/ # グローバル CLAUDE.md
      - ~/docs/doc/generated_files:/workspace/gen        # 生成ファイル保存用ディレクトリ
      - .:/workspace/.ccc                      # コンテナの配置場所
      - ..:/workspace:rw
      - ~/go/bin/cclog:/usr/bin/cclog
    working_dir: /workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    init: true
