services:
  claude-code-container_origin_name:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAIL_DOMAIN: ${MAIL_DOMAIN}
    env_file:
      - .env
    container_name: claude-code-container_origin_name
    volumes:
      - ~/docs/doc/_gen:/workspace/_gen        # 生成ファイル保存用ディレクトリ
      - ~/.claude:/home/ubuntu/.config/claude/ # グローバル CLAUDE.md
      - .:/workspace/.ccc                      # コンテナの配置場所
      - ..:/workspace:rw
    working_dir: /workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    init: true
