services:
  claude-code-container_origin_name:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAIL_DOMAIN: ${MAIL_DOMAIN}
    env_file:
      - .env
    container_name: claude-code-container_origin_name
    volumes:
      - ~/.claude:/home/ubuntu/.claude/
      - ~/.claude:/home/ubuntu/.config/claude/
      - .:/workspace/.ccc
      - ..:/workspace:rw
    working_dir: /workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    init: true
