services:
  claude-code-container_origin_name:
    image: origin_ccc:latest # ここでビルドしたイメージを全てに使う
    build:
      context: ${CCC_DIR}
      dockerfile: Dockerfile
    container_name: claude-code-container_origin_name
    volumes:
      - ${WORKSPACE_DIR}:/workspace:rw                   # Workspace Dir
      - ${CCC_DIR}:/home/ubuntu/.claude-code:ro            # Claude Code Container Dir
      - ~/.config/claude:/home/ubuntu/.config/claude/    # Global CLAUDE.md
      - ~/.config/nvim:/home/ubuntu/.config/nvim:ro      # Neovim config
      - ~/.config/gh:/root/.config/gh:ro                 # gh-cli config
      - ~/.codex/:/home/ubuntu/.codex                    # codex cli
    working_dir: /workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    init: true
