services:
  claude-code-container_origin_name:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    container_name: claude-code-container_origin_name
    volumes:
      - ./src/:/workspace:rw                             # Workspacce Dir
      - .:/workspace/.claude-code:ro                     # Claude Code Container Dir
      - ~/.config/claude:/home/ubuntu/.config/claude/   # Global CLAUDE.md
      - ~/.config/gh:/root/.config/gh:ro                 # gh-cli config
    working_dir: /workspace
    command: ["bash"]
    stdin_open: true
    tty: true
    environment:
      - TERM=xterm-256color
    init: true
