#!/bin/bash
# /usr/bin/dual_save MAILTITLE FILE_TITLE CONTENT_FILE

MAIL_TITLE="$1"
FILE_TITLE="$2"
CONTENT_FILE="$3"

# メール通知
/usr/bin/mail_notify "$MAIL_TITLE" --file "$CONTENT_FILE"

# ファイル保存
/usr/bin/archive_save "$FILE_TITLE" "$CONTENT_FILE"
