#!/usr/bin/env bash

TITLE=$1
shift
MESSAGE="$*"

escape_html() {
    printf '%s' "$1" | sed -e 's/&/\&amp;/g' \
                           -e 's/</\&lt;/g' \
                           -e 's/>/\&gt;/g' \
                           -e 's/"/\&quot;/g' \
                           -e "s/'/\&#39;/g"
}

ESCAPED_MESSAGE=$(escape_html "$MESSAGE")

curl -X POST 'https://api.resend.com/emails' \
    -H "Authorization: Bearer ${RESEND_TOKEN}" \
    -H 'Content-Type: application/json' \
    -d @- <<EOF
{
    "from": "${MAIL_FROM}",
    "to": ["${MAIL_TO}"],
    "subject": "${TITLE}",
    "html": "<pre>${ESCAPED_MESSAGE}</pre>"
}
EOF

